# Using Autograd in TensorFlow toSolve a Regression Problem

## Listing 3.1: A constant matrix defined in TensorFlow

In [1]:
import tensorflow as tf
x = tf.constant([1, 2, 3])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
(3,)
<dtype: 'int32'>


## Listing 3.2: A variable defined in TensorFlow

In [2]:
import tensorflow as tf
x = tf.Variable([1, 2, 3])
print(x)
print(x.shape)
print(x.dtype)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
(3,)
<dtype: 'int32'>


## Listing 3.3: Getting gradient in TensorFlow

In [3]:
import tensorflow as tf
x = tf.Variable(3.6)
with tf.GradientTape() as tape:
    y = x*x
dy = tape.gradient(y, x)
print(dy)

tf.Tensor(7.2, shape=(), dtype=float32)


## Listing 3.4: Defining a polynomial in NumPy

In [4]:
import numpy as np
polynomial = np.poly1d([1, 2, 3])
print(polynomial)

   2
1 x + 2 x + 3


## Listing 3.5: Using a polynomial

In [5]:
print(polynomial(1.5))

8.25


## Listing 3.6: Making samples from a polynomial

In [6]:
N = 20 # number of samples
# Generate random samples between -10 to +10
X = np.random.uniform(-10, 10, size=(N,1))
Y = polynomial(X)

## Listing 3.7: Regression on samples to discover the polynomial

In [7]:
import tensorflow as tf
# Assume samples X and Y are prepared elsewhere
XX = np.hstack([X*X, X, np.ones_like(X)])
w = tf.Variable(tf.random.normal((3,1))) # the 3 coefficients
x = tf.constant(XX, dtype=tf.float32) # input sample
y = tf.constant(Y, dtype=tf.float32) # output sample
optimizer = tf.keras.optimizers.Nadam(learning_rate=0.01)
print(w)
for _ in range(1000):
    with tf.GradientTape() as tape:
        y_pred = x @ w
        mse = tf.reduce_sum(tf.square(y - y_pred))
    grad = tape.gradient(mse, w)
    optimizer.apply_gradients([(grad, w)])
print(w)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 0.67356646],
       [-1.2872431 ],
       [-0.20029843]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.0067259],
       [1.9912688],
       [2.6677094]], dtype=float32)>


## Listing 3.8: Regression to discover a polynomial using TensorFlow

In [8]:
import numpy as np
import tensorflow as tf
N = 20 # number of samples
# Generate random samples between -10 to +10
polynomial = np.poly1d([1, 2, 3])
X = np.random.uniform(-10, 10, size=(N,1))
Y = polynomial(X)
# Prepare input as an array of shape (N,3)
XX = np.hstack([X*X, X, np.ones_like(X)])
# Prepare TensorFlow objects
w = tf.Variable(tf.random.normal((3,1))) # the 3 coefficients
x = tf.constant(XX, dtype=tf.float32) # input sample
y = tf.constant(Y, dtype=tf.float32) # output sample
optimizer = tf.keras.optimizers.Nadam(learning_rate=0.01)
print(w)
# Run optimizer
for _ in range(1000):
    with tf.GradientTape() as tape:
        y_pred = x @ w
        mse = tf.reduce_sum(tf.square(y - y_pred))
    grad = tape.gradient(mse, w)
    optimizer.apply_gradients([(grad, w)])
print(w)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 0.689684  ],
       [-1.7546302 ],
       [ 0.06169017]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.0047417],
       [1.9750314],
       [2.7365835]], dtype=float32)>


## Listing 3.9: Solving a math puzzle using TensorFlow

In [9]:
import tensorflow as tf
import random
A = tf.Variable(random.random())
B = tf.Variable(random.random())
C = tf.Variable(random.random())
D = tf.Variable(random.random())
# Gradient descent loop
EPOCHS = 1000
optimizer = tf.keras.optimizers.Nadam(learning_rate=0.1)
for _ in range(EPOCHS):
    with tf.GradientTape() as tape:
        y1 = A + B - 8
        y2 = C - D - 6
        y3 = A + C - 13
        y4 = B + D - 8
        sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
    gradA, gradB, gradC, gradD = tape.gradient(sqerr, [A, B, C, D])
    optimizer.apply_gradients([(gradA, A), (gradB, B), (gradC, C), (gradD, D)])
print(A)
print(B)
print(C)
print(D)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.500009298324585>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=4.499995708465576>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=9.499987602233887>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.4999959468841553>
