# Chương 18 Using Activation Functions in Neural Networks

## Sigmoid Function and Vanishing Gradient

In [2]:
import tensorflow as tf
from tensorflow.keras.activations import sigmoid
input_array = tf.constant([-1, 0, 1], dtype=tf.float32)
print(sigmoid(input_array))

tf.Tensor([0.26894143 0.5        0.7310586 ], shape=(3,), dtype=float32)


## Hyperbolic Tangent Function

In [6]:
import tensorflow as tf
from tensorflow.keras.activations import tanh
input_array = tf.constant([-1, 0, 1], dtype=tf.float32)
print(tanh(input_array))

tf.Tensor([-0.7615942  0.         0.7615942], shape=(3,), dtype=float32)


## Rectified Linear Unit (ReLU)

In [8]:
import tensorflow as tf
from tensorflow.keras.activations import relu
input_array = tf.constant([-1, 0, 1], dtype=tf.float32)
print(relu(input_array))

tf.Tensor([0. 0. 1.], shape=(3,), dtype=float32)


## Using Activation Functions in Practice

In [16]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Dense, Input, Flatten, Conv2D, BatchNormalization, MaxPool2D
from tensorflow.keras.models import Model

# Load CIFAR-10 dataset
(trainX, trainY), (testX, testY) = keras.datasets.cifar10.load_data()
# Define CNN model (inspired by LeNet-like structure)
input_layer = Input(shape=(32, 32, 3))
x = Conv2D(6, (5, 5), padding="same", activation="relu")(input_layer)
x = MaxPool2D(pool_size=(2, 2))(x)
x = Conv2D(16, (5, 5), padding="same", activation="relu")(x)
x = MaxPool2D(pool_size=(2, 2))(x)
x = Conv2D(120, (5, 5), padding="same", activation="relu")(x)
x = Flatten()(x)
x = Dense(units=84, activation="relu")(x)
x = Dense(units=10, activation="softmax")(x)

model = Model(inputs=input_layer, outputs=x)
# Model summary
model.summary()
# Compile model
model.compile(
    optimizer="adam",
    loss=tf.keras.losses.SparseCategoricalCrossentropy(),
    metrics=["accuracy"]
)
# Train model and save history
history = model.fit(
    x=trainX,
    y=trainY,
    batch_size=256,
    epochs=10,
    validation_data=(testX, testY)
)


170498071/170498071 ━━━━━━━━━━━━━━━━━━━━ 16s 0us/step


Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)             │ (None, 32, 32, 3)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d (Conv2D)                      │ (None, 32, 32, 6)           │             456 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 16, 16, 6)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 16, 16, 16)          │           2,416 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 8, 8, 16)            │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_2 (Conv2D)                    │ (None, 8, 8, 120)           │          48,120 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 7680)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 84)                  │         645,204 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 10)                  │             850 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 697,046 (2.66 MB)

 Trainable params: 697,046 (2.66 MB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/10
196/196 ━━━━━━━━━━━━━━━━━━━━ 8s 35ms/step - accuracy: 0.2195 - loss: 5.1687 - val_accuracy: 0.4217 - val_loss: 1.6309
Epoch 2/10
196/196 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.4610 - loss: 1.5268 - val_accuracy: 0.5005 - val_loss: 1.4108
Epoch 3/10
196/196 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.5407 - loss: 1.3044 - val_accuracy: 0.5279 - val_loss: 1.3484
Epoch 4/10
196/196 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.6026 - loss: 1.1249 - val_accuracy: 0.5434 - val_loss: 1.3174
Epoch 5/10
196/196 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - accuracy: 0.6558 - loss: 0.9863 - val_accuracy: 0.5536 - val_loss: 1.3114
Epoch 6/10
196/196 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - accuracy: 0.7029 - loss: 0.8469 - val_accuracy: 0.5454 - val_loss: 1.4058
Epoch 7/10
196/196 ━━━━━━━━━━━━━━━━━━━━ 8s 40ms/step - accuracy: 0.7478 - loss: 0.7213 - val_accuracy: 0.5487 - val_loss: 1.4300
Epoch 8/10
196/196 ━━━━━━━━━━━━━━━━━━━━ 7s 34ms/step - accuracy: 0.7916 - loss: 0.6026 - val_accu